### ISSUE TITLE
pull must unzip content

### ISSUE THREAD

**Issue by tank-bohr** [zerocracy/baza.rb#12]
To make the feature of content compression in pull operation work everywhere, we must support it in this library.

See also:
- https://github.com/yegor256/judges/issues/84
- https://github.com/zerocracy/baza/issues/115

**Comment by yegor256** [comment]
@tank-bohr what exactly is the problem here? I'm not sure the description is complete in this ticket, please make it more detailed

**Comment by tank-bohr** [comment]
It's an issue for me to be able to create a branch for #13. Otherwise, the bot is [yelling](https://github.com/zerocracy/baza.rb/pull/11#issuecomment-2294933861) at me

**Comment by yegor256** [comment]
@tank-bohr what is this issue about? What is the bug? What's wrong with the code? Just explain in the description what is wrong in this repo.

**Comment by tank-bohr** [comment]
@yegor256 description updated

**Comment by yegor256** [comment]
@tank-bohr got it, thanks

**Comment by 0crat** [comment]
@tank-bohr Hey there, bug hunter! 🐛 Great job spotting that issue - you've just snagged yourself 10 points! Your sharp eye is helping us level up our project quality. Got more [bugs in your sights](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html)? [Don't hold back](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html), [report away](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html)! Your current score is [101 points](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep those reports coming!

**Comment by tank-bohr** [comment]
@rultor release, tag is 0.0.7

**Comment by tank-bohr** [comment]
@yegor256, please help me release the gem to close this issue. Then I can proceed with https://github.com/yegor256/judges/issues/84.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.7`

**Comment by yegor256** [comment]
@tank-bohr we can close this one, right?
